[build-system]
requires = [
    "setuptools",
    "wheel",
    "pip",
    "cython"
]
build-backend = "setuptools.build_meta"
[tool.black]
line-length = 79
target-version = [
    "py36",
    "py37",
    "py38"
]
